"""Init

Revision ID: 0b2eaec0bd8a
Revises: 
Create Date: 2022-02-15 21:06:01.475093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2eaec0bd8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('sf_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('sf_id')
    )
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('savings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('stamp', sa.DateTime(), nullable=True),
    sa.Column('money_savings', sa.Numeric(), nullable=True),
    sa.Column('energy_savings', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.sf_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('billable_rate', sa.Numeric(), nullable=True),
    sa.Column('program', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_members')
    op.drop_table('savings')
    op.drop_table('programs')
    op.drop_table('customers')
    # ### end Alembic commands ###
